#!/bin/bash
echo "$(date +"%m-%d-%Y") : shutdown : $1 $2 $3" >> /var/log/openhab/restart.log 2>&1
SUDO=""
while getopts ":s" opt; do
  case $opt in
    s)
                SUDO="sudo"
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
shift $(($OPTIND - 1))
  /usr/bin/ssh -i /scripts/.ssh/id_rsa root@192.168.2.$1 "shutdown - now" >> /var/log/openhab/restart.log 2>&1
